fix: incorrect call to imported module
"comfy.model_management" was imported as "model_management", but in the code it still was called as "comfy.model_management".
This fixed my installation issue: 
NameError: name 'comfy' is not defined